### ISSUE TITLE
collaborators

### ISSUE THREAD

**Issue by DominiqueMakowski** [ClinicalBrainLab/SATA#1]
what I would then recommend is to go to Settings and add yourself and every relevant people as collaborators, so you can basically manage this package and make pull requests from your account the same as if this repo was yours (so you don't have to connect as the CBL everytime).

**Comment by DominiqueMakowski** [comment]
Also, I would recommend you to *watch* (i.e., follow) this repo with your account, so you will be notified via emails whenever there is some activity such as new issues or PRs

**Comment by ClinicalBrainLab** [comment]
> Also, I would recommend you to _watch_ (i.e., follow) this repo with your account, so you will be notified via emails whenever there is some activity such as new issues or PRs

Sure thanks
